### ISSUE TITLE
Работа над переводом

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-12-RUSSIAN#1]
MIUI12
В данной теме планируется оставлять информацию о том какие файлы планируются к допереводу и какие уже в процессе перевода (при совместном переводе), а также вопросы по переводу тех или иных строк.

**Comment by mclaude74** [comment]
Шаблоны:
[template_plurals.xml.txt](https://github.com/ingbrzy/MA-XML-12-RUSSIAN/files/4588609/template_plurals.xml.txt)
[template_strings.xml.txt](https://github.com/ingbrzy/MA-XML-12-RUSSIAN/files/4588610/template_strings.xml.txt)

**Comment by mclaude74** [comment]
На данный момент из [20.4.27] не переведены новые строки из

Health
MiLinkService
MiuiBluetooth
MiuiGallery
MMS
Music
Notes
QuickSearchBox

В остальные 42 приложения доперевод добавлен.

**Comment by mar1k94** [comment]
Добавьте эти строки ([Ссылка](https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/blob/2960f7dbf569b98c87ad0f436261520fc648b834/raphael/MiGalleryLockscreen.apk/res/values/strings.xml#L358) ) в русский перевод, а то на экране блокировки дата выглядит так: "Суббота 05/16"

```
<string name="miui_lock_screen_date_two_lines">"EEEE
d MMMM"</string>
<string name="miui_lock_screen_date_two_lines_12">"EEEE
d MMMM"</string>
<string name="miui_lock_screen_large_date">"EEEE
d MMMM"</string>
<string name="miui_lock_screen_large_date_12">"EEEE
d MMMM"</string>
<string name="miui_vertical_time_format_12">"hh
mm"</string>
<string name="miui_vertical_time_format_24">"HH
mm"</string>
```

**Comment by mclaude74** [comment]
@mar1k94, спасибо
Строки добавлены + добавлен перевод новых строк.
Также поправил формат даты приложении Часы.

https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commit/0087249760c1d93f2245d045af465734ac8a4bce#diff-9a9a556adf725bcbd918c40e8b7eda36

**Comment by mclaude74** [comment]
На данный момент [20.6.4] 

1) Все приложения в репозитории просканированы специально написанной для этого программой на старый недоперевод и допереведены (что означает практически 100% перевод в ресурсах, за исключением динамических строк с сервера).
2) Все приложения в репозитории просканированы на наличие опечаток и орфографии.
3) В Контакты добавлена алфавитная линейка без "избранного" и "цифр" (ограничение EU по количеству символов в алфавите - 26).

Изменения:
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commits/master/Russian/main

P.S.
Работа над улучшением перевода продолжается.

По замеченному недопереводу можно отписаться здесь:
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/issues/2

**Comment by zahid047** [comment]
![IMG_20200530_080740](https://user-images.githubusercontent.com/66158272/83327034-e8500900-a289-11ea-96bd-7bd240613b71.jpg)
Я поменял язык но не получилось(модел ми 6 20,5,28)

**Comment by zahid047** [comment]
![IMG_20200530_153217](https://user-images.githubusercontent.com/66158272/83327207-3e717c00-a28b-11ea-9e3b-3a91867f7a89.jpg)

**Comment by mclaude74** [comment]
@zahid047 
Прошивка устанавливалась начисто? Если нет, при установке прошивки поверх предыдущей, wipe cache и wipe Art/Dalvik cache делались?

Строки на втором скриншоте перевести пока нет возможности, они находятся в исходном коде приложения, а не в ресурсах для перевода.

По первому скриншоту:
Можно попробовать очистить данные приложения Настройки (зажать значок и выбрать Сведения. Очистка данных / Очистить все)

![Screenshot_2020-05-30-14-40-35-525_com miui securitycenter](https://user-images.githubusercontent.com/45774262/83327414-4548c080-a284-11ea-93f9-b808138ec606.jpg)

В дальнейшем, вопросы лучше размещать в теме Недоперевод (https://github.com/ingbrzy/MA-XML-12-RUSSIAN/issues/2)

**Comment by Gimler1940** [comment]
Сделайте пожалуйста перевод MIUI12 на Redmi Note 8 pro

**Comment by mclaude74** [comment]
@Gimler1940
Перевод MIUI12 общий для всех поддерживаемых устройств. Выпуск прошивок для конкретных устройств от меня не зависит.

По поводу Redmi Note 8 pro (begonia) xiaomi.eu опубликовали у себя пост (перевод ниже):
https://xiaomi.eu/community/threads/xiaomi-eu-hmnote8pro-mtk-begonia-support.53542/

Мы отказались от поддержки HMnote8Pro MTK [бегония] из-за большого количества "окирпиченных" устройств, вызванных установкой TWRP или Magisk или любых других модов. MTK не позволяет загружаться в Fastboot, если что-то «идет не так», после чего пользователи вынуждены прошивать свое устройство через  Режим EDF SPFlash Tool, который используется Xiaomi только для нескольких авторизованных учетных записей.. Поэтому, для безопасности пользователей, мы не будем выпускать какие-либо пришивки для этого устройства.
PS: мы не рекомендуем покупать устройства MTK, если вы хотите использовать наши прошивки.
