### ISSUE TITLE
Translation of a line of letters in Contacts

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-12-RUSSIAN#18]
@ingbrzy 

How to add a translation for the letters shown in the screenshot?

![IMG_20200516_183639](https://user-images.githubusercontent.com/45774262/82124008-1d962a80-97a5-11ea-8b01-b74c324952c9.jpg)

**Comment by mclaude74** [comment]
@ingbrzy 
many thanks for help!

**Comment by mclaude74** [comment]
@ingbrzy 

The translation for the letters still missing.
Last time I adjusted the resource so that the number of elements matches the number in the English alphabet. But there is no translation in this build anyway.
I disassembled the application Contacts.apk and looked at the resources:
     <string-array name = "alphabet_table">
     <string-array name = "alphabet_table_with_starred">
are absent in arrays.xml

https://github.com/ingbrzy/MA-XML-12-RUSSIAN/blob/732925017f712d3da086cb610e2c2dc6d08aceb5/Russian/main/Contacts.apk/res/values-ru/arrays.xml#L3-L65

Maybe I did something wrong?
Thanks in advace.

UPD. 
English letters = 26. Do I need to reduce the number of letters in russian translation to 26?

**Comment by ingbrzy** [comment]
fixed for next release
https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/commit/b9d71b0c99b10d9a793b9ea82b1a40cbc8a75ff9
