### ISSUE TITLE
Недоперевод

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-12-RUSSIAN#2]
В данной теме можно сообщать о недопереводе.
Желательно указывать:
1) версию прошивки, устройство (имя и кодовое слово)
2) приложение, строки на английском либо скриншот.

**Актуальная, по возможности, информация будет размещаться во втором посте. 
Пожалуйста, прочтите его перед размещением своего поста - возможно, там есть ответ.**

Тема будет периодически очищаться от старых постов. 

**Дополнение:**

Объясню ситуацию по переводу в целом.
xiaomi.eu - европейское сообщество, основной язык - английский. Русский перевод идет бонусом.
Перевод на другие языки делается энтузиастами.

Раньше перевод попадал в прошивку из глобальных прошивок за счет самих xiaomi.eu,
с опозданием и с большим количеством недоперевода ввиду различий между глобальными и китайскими прошивками.
Целенаправленным переводом на русский для xiaomi.eu раньше никто не занимался и мало кто этим хочет заниматься.

Я - обычный пользователь, как и вы, к xiaomi.eu отношения практически не имею, на сборку прошивок, а также на то что берется из репозитория для сборки, повлиять не могу. Я только добавляю перевод в репозиторий для русского перевода.

Занимаюсь этим безвозмездно, на личном энтузиазме, в личное свободное время. Это дело отнимает достаточно много времени. Просьба отнестись с пониманием.

**Comment by mclaude74** [comment]
Редактируемый пост:

**Текущая прошивка [20.7.30]** 

1) Ресурсы приложений в репозитории перевода просканированы специально написанной для этого программой на старый недоперевод и допереведены.

2) Ресурсы приложений в репозитории перевода просканированы на наличие явных опечаток и ошибок в орфографии (за исключением ресурсов в arrays и plurals).

3) В Контакты добавлена алфавитная линейка без "избранного" и "цифр" и (ограничение по количеству символов в английском алфавите - 26). Расширение алфавита  - под вопросом.

4) Строки в Устройство, такие  как "inches" и "mAh(typ)" являются динамическими (приходят с сервера), изменять их на статические, для возможности перевода, EU не планирует.

**На данный момент есть небольшой недоперевод в приложении Почта (новые строки от 20.7.29)**

**Изменения в переводе можно посмотреть здесь:**
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commits/master/Russian/main

**Comment by BineCelfi** [comment]
Mi 8, прошивка MIUI 12 EU 20.4.30
![image](https://user-images.githubusercontent.com/25923963/81207402-c9818e00-8fcd-11ea-8a63-e38d9e461d75.png)
![image](https://user-images.githubusercontent.com/25923963/81207429-d1d9c900-8fcd-11ea-9e5d-74cda31dadef.png)
![image](https://user-images.githubusercontent.com/25923963/81207450-d69e7d00-8fcd-11ea-8e2b-180e704aee1a.png)
![image](https://user-images.githubusercontent.com/25923963/81207478-e322d580-8fcd-11ea-9ba0-33a039822eff.png)

**Comment by BineCelfi** [comment]
Еще в настройках Тема пишется на английском и на Always-on display пишется PM AM после дня недели
![image](https://user-images.githubusercontent.com/25923963/81207814-75c37480-8fce-11ea-925e-4c7419a54295.png)
![image](https://user-images.githubusercontent.com/25923963/81207819-78be6500-8fce-11ea-964c-de54ffc2a28b.png)
![image](https://user-images.githubusercontent.com/25923963/81207827-7bb95580-8fce-11ea-8dfa-994fc4bb3041.png)

**Comment by Totozao** [comment]
@mclaude74 могу помочь с оставшимся строками. Скажи что тебе ещё надо перевести.

**Comment by mclaude74** [comment]
@Totozao, спасибо!
Нам тогда лучше в эту ветку. Позже в Телеграм свяжусь.
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/issues/1

Из недоперевода см. приложения 
Health, MiLinkService, MiuiBluetooth, MiuiGallery, MMS, Music, Notes, QuickSearchBox
в ветке 
https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/tree/master/Diff_MIUI12-MIUI11
Нам нужны файлы с _not_translated, там собраны новые строки.

**Comment by Totozao** [comment]
Ок, буду ждать

**Comment by mclaude74** [comment]
@BineCelfi 
Доперевод уже добавлен. 
По поводу "Always-on Display"
У меня телефон с не Amoled-дисплеем поэтому проверить корректность и полноту перевода  нет возможности. Добавил адаптацию даты на русский, правда, не вижу наложения AM/PM на дату, возможно это косяк расположения элементов.
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/blob/3918d99afab25ed62e88e32fff838c647b206ead/Russian/main/MiuiAod.apk/res/values-ru/strings.xml#L41-L49

**Comment by BineCelfi** [comment]
Если поможет то на чешском этого нет, пишется полностью день недели без сокращения.

**Comment by mclaude74** [comment]
@BineCelfi 
Да, нашел. Спасибо! На английском опечатка. 
https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/blob/eb871f673d9f64e4bc7f0f83f8c2d80ab666bc9b/Diff_MIUI12-MIUI11/MiuiAod.apk/res/values/strings_not_translated.xml#L30-L33
У чехов исправленный вариант. Добавил.
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/blob/07165b88031b70bfb6be97de4835dba343b0f648/Russian/main/MiuiAod.apk/res/values-ru/strings.xml#L211-L214

**Comment by mar1k94** [comment]
@mclaude74 координаты и иероглифы это в приложении Темы, в суперобоях Дом
![Screenshot_2020-05-07-03-34-33-891_com miui miwallpaper](https://user-images.githubusercontent.com/8592709/81241780-ef318600-9013-11ea-87da-8c74284fb841.jpg)
___________

![Screenshot_2020-05-06-20-22-35-233_com miui zman](https://user-images.githubusercontent.com/8592709/81241821-11c39f00-9014-11ea-92f4-f3be43a2dcf4.jpg)

![IMG_20200507_033933](https://user-images.githubusercontent.com/8592709/81241950-754dcc80-9014-11ea-82ef-2c2736a755e5.jpg)

**Comment by mclaude74** [comment]
@mar1k94 
В MIUI12 появилось новое приложение ZMan (Безопасный обмен). Доперевод попадет только в следующую сборку. 
Пробелы уже добавлены.

**Comment by mar1k94** [comment]
@mclaude74 
![IMG_20200509_002949](https://user-images.githubusercontent.com/8592709/81451529-66d6f080-918d-11ea-8205-bd985498f75e.jpg)
![IMG_20200509_002903](https://user-images.githubusercontent.com/8592709/81451531-68081d80-918d-11ea-8401-3bceb6052c94.jpg)
raphael miui 20.5.7

**Comment by mclaude74** [comment]
@mar1k94 
Доперевод пункта в Строка состояния сделан. 
Режим медитации, иероглифы - это уже на стороне EU.

**Comment by Ivan-Gorchakov** [comment]
1. MIUI 12 (20.5.7) Beta, MI Note 10 Pro
2. Виджет погоды: 
![IMG_20200511_075912](https://user-images.githubusercontent.com/30525592/81525693-2f6b6e00-935e-11ea-82b7-3803de912e1b.jpg)

**Comment by mclaude74** [comment]
@Ivan-Gorchakov 
Вы ставили прошивку начисто или поверх? Если поверх, art/dalvick cache и cache чистили при установке?
На моём устройстве перевод есть.
![Screenshot_2020-05-11-16-37-49-128_com miui home](https://user-images.githubusercontent.com/45774262/81573340-045c3b00-93ad-11ea-9f8d-a0f9d2800abb.jpg)

**Comment by Ivan-Gorchakov** [comment]
@mclaude74 начисто, но dalvick/cache по-моему не чистил... точно не помню.

**Comment by mclaude74** [comment]
@Ivan-Gorchakov 
А если удалить виджет и добавить заново?

**Comment by Ivan-Gorchakov** [comment]
> @Ivan-Gorchakov 
> А если удалить виджет и добавить заново?

Не помогло.

**Comment by mclaude74** [comment]
Как вариант, попробовать удалить хвосты приложений в папке Android/data, перезагрузиться в рекавери, почистить кэши.

Сделал поиск в репозиториях, все встречающиеся слова Clear переведены. Если только не глюк сборки для конкретного устройства со стороны EU.

**Comment by mar1k94** [comment]
@mclaude74 при первом заходе в заметки 
![IMG_20200512_225816](https://user-images.githubusercontent.com/8592709/81739833-ad399180-94a4-11ea-98cf-524f1055f05c.jpg)

**Comment by mclaude74** [comment]
@mar1k94, перевод уже добавлен

**Comment by Ivan-Gorchakov** [comment]
> Как вариант, попробовать удалить хвосты приложений в папке Android/data, перезагрузиться в рекавери, почистить кэши.
> 
> Сделал поиск в репозитории, все встречающиеся слова Clear переведены. Если только не глюк сборки для конкретного устройства со стороны EU.

Вылечил: в настройках переключил на Английский, после этого вернул Русский-и теперь виджет погоды переведен 🙂

**Comment by mclaude74** [comment]
@Ivan-Gorchakov,
спасибо за информацию :)

**Comment by bagdasarov** [comment]
MIX3 (perseus) - стоковая галерея вообще без перевода. Пару недель назад был баг с галереей на Perseus. Его оперативно вылечили. Но заменили APK на версию без русского перевода. И с тех пор уже пару релизов так и продолжается.

**Comment by mclaude74** [comment]
@bagdasarov 
Обновления для Галереи не устанавливались?
На сборку прошивок повлиять возможности нет, я только наполняю репозиторий перевода, он общий для всех прошивок. На Mi Max 3 Галерея с русским переводом.
При глюках перевода можно попробовать очистить кеш и данные приложения, а также переключиться на другой язык и обратно.
Как вариант - попробовать Галерею из прошивки для другого устройства.

**Comment by bagdasarov** [comment]
> Обновления для Галереи не устанавливались?
Х-мм. Действительно. Стояла v3.0-20190619. Удалил обновления, стало v2.2.16.3. И русский перевод есть. Спасибо.

**Comment by Seamantypok** [comment]
Недоперевод ,miui 12 beta 20.5.21 
При переходе в новую функцию окна любого приложения сверху текст на англ
![IMG_20200523_225814_951](https://user-images.githubusercontent.com/65829894/82739563-2492df00-9d49-11ea-918d-803bdd6e234b.jpg)

**Comment by mclaude74** [comment]
@Seamantypok 
спасибо, добавил
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commit/8ff844c394c55cd43c6f7facfe8d4e7885622683#

**Comment by mclaude74** [comment]
@mar1k94 
@BineCelfi 
@Ivan-Gorchakov 
@Seamantypok 
@bagdasarov 

Небольшой опрос. 
В Контактах, чтобы появились русские буквы в алфавитной линейке, необходимо чтобы было 26 символов, как в английском варианте. 

Я попробовал выкинуть символ ! (Избранное) и # (Цифры).

Надо решить, оставить так, либо пожертвовать какой-либо буквой в пользу Избранного или Цифр

Одно из мнений было - убрать Щ и оставить Избранное.
Какой вариант предпочтительнее?

![Screenshot_2020-05-30-03-20-35-714_com android contacts](https://user-images.githubusercontent.com/45774262/83325528-943b2980-a275-11ea-89aa-8302f184bb87.jpg)

**Comment by mar1k94** [comment]
@mclaude74 избранные и так вверху списка, поэтому можно и не добавлять их на линейку.  вариант как на скриншоте выше меня вполне устраивает

**Comment by zahid047** [comment]
![IMG_20200530_153217](https://user-images.githubusercontent.com/66158272/83327316-ad4ed500-a28b-11ea-9573-dda55accf084.jpg)

**Comment by zahid047** [comment]
![IMG_20200530_080740](https://user-images.githubusercontent.com/66158272/83327324-b50e7980-a28b-11ea-95a7-1c077d947b07.jpg)
я поменял язык но не получилось(модел ми 6 20,5,28)

**Comment by mclaude74** [comment]
@zahid047 
Прошивка устанавливалась начисто? Если нет, при установке прошивки поверх предыдущей, wipe cache и wipe Art/Dalvik cache делались?

Строку **inches** перевести пока нет возможности, она находятся в исходном коде приложения, а не в ресурсах для перевода.

По поводу Даты и времени:
Можно попробовать очистить данные приложения Настройки (зажать значок и выбрать Сведения. Очистка данных / Очистить все)

![Screenshot_2020-05-30-14-40-35-525_com miui securitycenter](https://user-images.githubusercontent.com/45774262/83327414-4548c080-a284-11ea-93f9-b808138ec606.jpg)

**Comment by bagdasarov** [comment]
Поддерживаю
От: 	mar1k94 notifications@github.com
Дата: 	30 мая 2020 г. 14:12:27
Кому: 	ingbrzy/MA-XML-12-RUSSIAN MA-XML-12-RUSSIAN@noreply.github.com
Копия: 	bagdasarov ilia.bagdasarov@gmail.com, Mention 
mention@noreply.github.com
Тема: 	Re: [ingbrzy/MA-XML-12-RUSSIAN] Недоперевод (#2)

**Comment by Borland30** [comment]
> Надо решить, оставить так, либо пожертвовать какой-либо буквой в пользу Избранного или Цифр

Оставить так, как есть. С полным алфавитом, без цифр/избранного.

**Comment by Dialynx** [comment]
![Screenshot_2020-05-31-22-05-07-640_com android settings](https://user-images.githubusercontent.com/39007815/83360625-4284c300-a38b-11ea-86eb-87c14a39770f.jpg)
Вот здесь коряво перевод встал

**Comment by mclaude74** [comment]
@Dialynx 
На MIUI12 это исправлено. Сейчас перевод для конкретного случая сейчас выглядит так:

https://github.com/ingbrzy/MA-XML-12-RUSSIAN/blob/af6b8b309116420fce70db10d666a20eac96dc59/Russian/main/Settings.apk/res/values-ru/strings.xml#L4981

**Comment by bagdasarov** [comment]
20.6.11 Mix3 (perseus)
Меню \ Время экрана.  иероглифы


- 
С уважением,
Илья Багдасаров
Tel. 	+373 /79/ 888899
Skype  ilia.bagdasarov
linkedin.com/in/bagdasarov <http://www.linkedin.com/in/bagdasarov>_________________________________________
This e-mail originates from  <mailto:%C2%A0ilia.bagdasarov@gmail.com>ilia.bagdasarov@gmail.com <mailto:ilia.bagdasarov@gmail.com>
‌‌
‌‌
‌‌

‌‌

**Comment by mclaude74** [comment]
@bagdasarov 
Об этом известно. Это, скорее, проблема не перевода, а сборки. На других языках та же проблема. На своем телефоне удалось побороть так: переключиться на английский, потом обратно. Применить заново стандартную тему (обычно только значки применяю), затем перезагрузить телефон. 
![image](https://user-images.githubusercontent.com/45774262/84549597-0baa9780-ad11-11ea-89c7-77f2bfca62b8.png)

**Comment by Seamantypok** [comment]
Mi 9T , miui 12 eu 20.6.11 при повороте экрана в шторке уведомлений сверху китайщина 
![IMG_20200618_175025](https://user-images.githubusercontent.com/65829894/85036593-fd370280-b18c-11ea-93ed-93ad604d3d28.jpg)

**Comment by bagdasarov** [comment]
MIX3 20.6.18
Что-то по польски?

сб, 13 июн. 2020 г., 00:29 Ilia Bagdasarov <ilia.bagdasarov@gmail.com>:

> 20.6.11 Mix3 (perseus)
> Меню \ Время экрана.  иероглифы
>
>
>
> *- С уважением,Илья БагдасаровTel.  +373 /79/
> 888899Skype  ilia.bagdasarovlinkedin.com/in/bagdasarov
> <http://www.linkedin.com/in/bagdasarov>_________________________________________This
> e-mail originates from
> <%C2%A0ilia.bagdasarov@gmail.com>ilia.bagdasarov@gmail.com
> <ilia.bagdasarov@gmail.com>‌‌*
> ‌‌
> ‌‌
>
> ‌‌
>

**Comment by mar1k94** [comment]
<string name="photo_editor_text">Текст</string>
  <string name="photo_editor_text">Водяной знак</string>

зачем поменяли? в фоторедакторе это текст все-таки а не водяной знак, там даже пиктограмма Т есть!  верните обратно текст

**Comment by mclaude74** [comment]
> зачем поменяли? в фоторедакторе это текст все-таки а не водяной знак, там даже пиктограмма Т есть! верните обратно текст

Это инициатива китайцев. Они поменяли исходный текст, соответственно была реакция на это.
https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/commit/e41797ee40f337d7560cc47b0d3b787b6fe62515#diff-058830a9d4e68f9c8b06286f644bbe18L1792

Хорошо, верну старый перевод.

**Comment by mclaude74** [comment]
@bagdasarov 
> Что-то по польски?
Пришлите скриншот, не совсем понятно о чем идет речь.

**Comment by ghost** [comment]
Mi9SE, 12.0.1.0 stable.

Ошибка перевода в стоковой камере: "Экспозиция" вместо "Выдержка"

![IMG_20200725_021012](https://user-images.githubusercontent.com/68759607/88442129-04040580-ce1c-11ea-887f-a79d61083db0.jpg)

**Comment by mclaude74** [comment]
@AnyDeath 
Поправлено.

**Comment by Fan4eG-dev** [comment]
Redmi Note 8, MIUI 12 20.7.23 beta.

Пожалуйста, исправьте отображение даты в центре управления на русском языке, сделайте его сокращенным. Сегодняшняя дата - «воскресенье», и у нас  это громкое слово, так что в центре управления все идет вниз. Пожалуйста, сделайте дату сокращенной, чтобы день недели не был полным, а был сокращенным.
![IMG_20200726_101058](https://user-images.githubusercontent.com/68805627/88474625-2cc9ef00-cf31-11ea-8bd3-813f7db41a68.jpg)

**Comment by mclaude74** [comment]
@Fan4eG-dev, правка внесена 
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commit/3d0bed18651b9ed1aac8263cb48c0bcaf8073ced#diff-9a9a556adf725bcbd918c40e8b7eda36

Отображение может меняться темой
`<string name="status_bar_clock_date_weekday_format">E, d MMMM</string>`

P.S. В моем случае день недели и дата вписываются в одну строку - зависит от шрифта

**Comment by Fan4eG-dev** [comment]
Как мне теперь внести эту правку, чтобы у меня на телефоне сокращённо дата отображалась?

**Comment by Fan4eG-dev** [comment]
Redmi Note 8, MIUI 12 20.7.23 beta.

Сделайте пожалуйста сокращённые дни недели в центре уведомлений, т.к погода из-за длинных слов недели некорректно отображается.
![IMG_20200728_083342](https://user-images.githubusercontent.com/68805627/88623173-134db200-d0ad-11ea-9b0f-5796a775d8ea.jpg)

**Comment by mclaude74** [comment]
@Fan4eG-dev  
В предыдущем посте правка общая для этих ситуаций

**Comment by Fan4eG-dev** [comment]
Redmi Note 8, MIUI 12 20.7.30 beta.
Ну и смысл от таких отчётов? Я сделал отчёт чтобы Вы сделали дату сокращённой, после сегодняшнего релиза ничего не поменялось, как была дата так и осталось. В чем проблема сделать её сокращённой чтобы пятница отображалась "Пт" и также с другими днями недели. 
![IMG_20200731_095029](https://user-images.githubusercontent.com/68805627/89010132-aa697280-d316-11ea-9afb-fa53dc0214df.jpg)

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Ну и смысл от такого тона?

Объясню ситуацию в целом. 
xiaomi.eu - европейское сообщество, основной язык - английский. Русский перевод идет бонусом.
Перевод на другие языки делается энтузиастами. 

Раньше перевод попадал в прошивку из глобальных прошивок за счет самих xiaomi.eu, 
с опозданием и с большим количеством недоперевода ввиду различий между глобальными и китайскими прошивками.
Целенаправленным переводом на русский для xiaomi.eu раньше никто не занимался и мало кто этим хочет заниматься.

Я - обычный пользователь, к xiaomi.eu отношения практически не имею, на сборку прошивок, а также на то что берется из репозитория для сборки, повлиять не могу . Я только добавляю перевод в репозиторий для русского перевода.

Занимаюсь этим безвозмездно, на личном энтузиазме, в личное свободное время. Это дело отнимает достаточно много времени. И, по сути, я никому ничего не должен и не обязан этим заниматься, у меня хватает своих дел.

Сокращение даты добавил, при тестировании через "механизм тем" дата у меня отображалась в сокращенном варианте.

![image](https://user-images.githubusercontent.com/45774262/89029111-5c646700-d336-11ea-816c-e00d0c0f7939.png)

Почему дата отображается иначе - надо будет разобрать прошивку и посмотреть, учли ли xiaomi.eu изменения в репозитории при сборке.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Просмотрел, в прошивке дата в коротком формате, но она не применяется. Не знаю почему, и этот вопрос к EU или китайцам.

Единственный способ сделать короткое отображение - через "механизм тем" (я так тестирую перевод, без разбора прошивки), который имеет повышенный приоритет при использовании ресурсов и работает, судя по всему.

Ссылку на файл ресурсов com.android.systemui разместил в [теме](https://xiaomi.eu/community/threads/date-display-in-the-control-center-in-russian.56757/post-554977).
Его можно положить через файловый менеджер по пути /system/media/theme/default (если есть ROOT) и перезагрузить устройство.
Либо через файловый менеджер TWRP, предварительно смонтировав SYSTEM, положив по пути    
/system/system/media/theme/default

Если используется сторонняя тема, способ может не сработать.

На данный момент это все что можно сделать и проблема не в переводе.

**Comment by Fan4eG-dev** [comment]
Спасибо за способ, извините за беспокойство.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
В теме xiaomi.eu добавил патч и описал эксперименты. 
На английском языке формат даты в Центре управления имеет длинный формат и на него влияет тот же патч.
Почему не применяется короткий формат через ресурсы перевода, но применяется через "механизм тем" у меня понимания нет. Возможно разработчик Igor Eisberg что-то подскажет.

**Comment by Fan4eG-dev** [comment]
Будем ждать ответа, самому очень интересно что он скажет по этому поводу.

> @Fan4eG-dev
> В теме xiaomi.eu добавил патч и описал эксперименты.
> На английском языке формат даты в Центре управления имеет длинный формат и на него влияет тот же патч.
> Почему не применяется короткий формат через ресурсы перевода, но применяется через "механизм тем" у меня понимания нет. Возможно разработчик Igor Eisberg что-то подскажет.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Будем ждать ответа, самому очень интересно что он скажет по этому поводу.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Сам недавно с МиРум перешёл из-за того что они прекратили разработку своих прошивок, последнее обновление было - 20.7.9, там где и добавили время с датой в центре управления и она там сразу из коробки шла с сокращённой датой, поэтому, после перехода на xiaomi eu очень сильно начало кидаться в глаза переход на другую строку с датой, т.к она тут не сокращённая. Вот из-за этого захотелось предложить исправление, потому что так будет выглядеть лучше. Я понимаю что русский язык в этой прошивке это как дополнение, но возможно можно как-то это реализовать, если получится я могу попробовать связаться с разработчиком МиРум и расспросить как он это реализовал и тогда можно будет что-то сделать.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Мирум:
`   <string name="status_bar_clock_date_format">EEE, d MMMM</string>`
`   <string name="status_bar_clock_date_format_12">EEE, d MMMM</string>`
`    <string name="status_bar_clock_date_time_format">H:mm | EEE, d MMMM</string>`
`    <string name="status_bar_clock_date_time_format_12">aah:mm | EEE, d MMMM</string>`
`    <string name="status_bar_clock_date_weekday_format">EEE, d MMMM</string>`
`    <string name="status_bar_clock_date_weekday_format_12">EEE, d MMMM</string>`
ЕУ:
`    <string name="status_bar_clock_date_format">EEEE, d MMMM</string>`
`    <string name="status_bar_clock_date_format_12">E, d MMMM</string>`
`    <string name="status_bar_clock_date_time_format">H:mm E, d MMMM</string>`
`    <string name="status_bar_clock_date_time_format_12">h:mm aa, E, d MMMM</string>`
`    <string name="status_bar_clock_date_weekday_format">E, d MMMM</string>`
`    <string name="status_bar_clock_date_weekday_format_12">E, d MMMM</string>`

На EU "EEE" и "E" дают короткий формат недели.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Я пообщался с одним человеком и у него стоит стабильная версия xiaomi eu. Так вот, самое странное то, что у него дата сокращённая в центре уведомлений, т.к в центре управления ещё не завезли дату с временем в стабильной версии, но она у него сокращена в центре уведомлений, а на еженедельной почему-то она не сокращается в центре управлении и в центре уведомлении и из-за этого ещё погода с городом не влазит и постоянно ездит, выглядит не особо. 
![1596232846](https://user-images.githubusercontent.com/68805627/89080761-7b90e200-d392-11ea-884b-f5458da6c1bd.jpg)
![1596232849](https://user-images.githubusercontent.com/68805627/89080763-7cc20f00-d392-11ea-9a5d-dab0bcaf2274.jpg)

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Странно то, что база перевода одна общая и для еженедельных и для стабильных.
Если есть возможность прямо с телефона со стабильной EU достать MiuiSystenUI.apk для сравнения, было бы хорошо.
Если изменений не обнаружится, то проблема может быть в коде а не переводе.

P.S. Т.к. я использую модифицированный штатный шрифт, проблемы не замечал.

Надо понимать, что Мирум - глубокая локализация + некоторая адаптация кода (на что EU не всегда соглашается).

**Comment by Fan4eG-dev** [comment]
Извините пожалуйста за вопрос, возможно я наглею, но почему в началее в коде от EU используется 4 (EEEE), когда в МиРум их 3 (EEE)?
![IMG_20200801_011552](https://user-images.githubusercontent.com/68805627/89081692-93696580-d394-11ea-870c-0e0bc3c95a46.jpg)
?

**Comment by mclaude74** [comment]
Эксперименты показали, что это значение влияет на формат недели в обычной шторке уведомлений. 
У меня сейчас в центре управления - короткое написание недели (с патчем).
В классической шторке - длинное написание недели.

Я могу поменять и в классической на короткое написание. Посмотрим тогда в следующем релизе, изменится ли дата без патча. Центром уведомлений не пользуюсь - т.к. он очень плохо реагирует на нажатия (это конкретная проблема только для Mi Max 3)  

[ KNOWN CHINA ISSUES ]
Control center: Quick toggles not reacting to touches properly. [Mi Max 3 only]
Settings: Crashes when tapping "Accessibility" search result.

**Comment by Fan4eG-dev** [comment]
@mclaude74 кстати, сейчас я удалил патч который с помощью рут прав ставил и попробовал прошить zip установщик который вы мне скинули на форуме, все прошилось без ошибок, но после перезагрузки обратно в систему ничего не поменялось, в принципе неважно я могу и через рут ставить, но все же установщик тот почему-то не сработал.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Штатный TWRP (который от Мирум)?
Если перед запуском смонтировать в TWRP system, патч сработает?
У меня FOX рекавери. Проверю у себя.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Попробуйте поменять и в классической, почему-то у меня есть предположение  что это может сработать, потому что в МиРум в классической шторке дата сокращена. Скриншот ниже.
![1596234740](https://user-images.githubusercontent.com/68805627/89082568-07a50880-d397-11ea-81be-f9c3b7c2487c.jpg)

**Comment by mclaude74** [comment]
> Попробуйте поменять и в классической
Ок. [Правка](https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commit/8e0b2d86e354b4f2e3db3c980318e921ef72d1e5#diff-9a9a556adf725bcbd918c40e8b7eda36) внесена. В следующем релизе увидим.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Хорошо, ждём.

Да у меня TWRP от МиРум, уже не буду заново загружаться пробовать, попробую днём и отпишу будет ли работать.

**Comment by mclaude74** [comment]
> Да у меня TWRP от МиРум, уже не буду заново загружаться пробовать, попробую днём

Проверил патч, у меня срабатывает. Видимо FOX по-другому обрабатывает патчи. 
На форуме EU встречал рекомендации монтировать system при использовании патчей в TWRP.  
В скрипте есть монтирование system. Почему не сработал в штатном TWRP надо разбираться.
Но скорее всего, патч не понадобится в следующем релизе.

И выяснили следующую проблему - перевод в ресурсах и через "механизм тем" не всегда работает одинаково.
Пересобирать прошивки для проверки перевода у меня нет возможности (и намного дольше). 
Плюс еще недавно выяснилось, что для отдельных устройств надо дублировать перевод некоторых приложений и править часть строк (так организован репозиторий перевода) - тот еще геморрой.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Спасибо вам большое что вообще занимаетесь этим, это понятно что это ещё тот геморрой, но если бы не вы то были бы недопереводы, приходилось бы ждать когда EU из официальных прошивок возьмут перевод. Ухх, надеюсь уже в следующей обнове будет всё нормально, ну а если нет, то с помощью патча буду тогда накатывать. Даже нельзя представить не прочувствовав на своей шкуре какого это каждую неделю прошивки выпускать, китайцы выпустят - ее надо скачать, потом локализировать, а ещё бывает очень много проблем, сделать это для немаленького списка девайсов, а это сложно и геморойно, а потом ещё выгрузить на сервера для того чтобы пользователи могли обновится через ОТА, либо скачать прошивку и вручную через TWRP, уходит однако как подумаешь об всем этом очень много времени, вот поэтому спокойно можно понять разработчика МиРум, тем более он один у них делал прошивки под большое количество телефонов и там понятное дело жизнь уже уходила на второй план.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Спасибо )
Китайцы очень плодовитые, с пн по чт несколько бет выходит.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
А это только так с MIUI 12, что китайцы беты начали делать с пн по чт? или так было и с MIUI 11? Просто если я ничего не путаю то там просто выходило обновление раз в четверг и тогда не было таких частых обновлений.

**Comment by mclaude74** [comment]
@Fan4eG-dev
В MIUI 11 тоже так же было. Локализаторы просто объединяют в итоговую четверговую. [Пример](https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/commits/master/dipper).
Т.к. EU в четверг вечером выпускают прошивки (там же английский основной, нет проблем), бывает сложно угнаться. Из-за этого сложилась репутация не полностью переведенной прошивки.  
У Мирум в этом плане было время до пн и возможность адаптировать новшества, которые EU могли придержать до следующего релиза.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Есть [ответ](https://xiaomi.eu/community/threads/date-display-in-the-control-center-in-russian.56757/post-555080) от разработчика EU. Так или иначе, в следующем релизе д.б. исправлено.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Надеюсь на это :)
Ждём-с.

**Comment by Fan4eG-dev** [comment]
@mclaude74 
Может почистите тут половину сообщений, а то как-то много спама в теме развелось из-за меня.

**Comment by mclaude74** [comment]
@Fan4eG-dev 
Открою новую тему, продублирую первые посты

**Comment by bagdasarov** [comment]
Добрый день,

Прошу внести ясность в эту опцию (MIX3 20.8.6, но то же самое и на других аппаратах).
Что такое «ночной режим» в настройках яркости ? В прошивках XIAOMI.EU MIUI 12.1 beta такой опции нет (и на более ранних тоже не помню).
На глобалках есть т.н. "ночной режим»: отдельная кнопка и настройки.

Вопрос: если эта опция переведена правильно (в английском тоже Night mode), то как получить доступ к этому «ночному режиму» на прошивках xiaomi.eu <http://xiaomi.eu/> ?
Если это настройки минимальной яркости в «тёмном режиме», то тогда нужно переименовать её тут во избежание недоразумений.
Если всё правильно переведено, но на xiaomi.eu <http://xiaomi.eu/> разрабы где-то «потеряли» ночной режим, то может просто удалить эту опцию из меню дабы не смущать юзеров.
 

 





- 
С уважением,
Илья Багдасаров
This e-mail originates from  <mailto:%C2%A0ilia.bagdasarov@gmail.com>ilia.bagdasarov@gmail.com <mailto:ilia.bagdasarov@gmail.com>
‌‌
‌‌
‌‌

‌‌

**Comment by mclaude74** [comment]
@bagdasarov 
Да, есть "dark mode" и "night mode". Как работает второй режим не разобрался, вернее, не нашел на что он влияет.
Я могу повлиять только на перевод. По поводу удаления этой опции, надо написать в [теме](https://xiaomi.eu/community/threads/weekly-confirmed-issues-faq.46800/) на форуме xiaomi.eu
