### ISSUE TITLE
multilang_filter

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-12-RUSSIAN#31]
@ingbrzy 
Some "format mismatch" has already been fixed. Why not removed from the list?
As example for
Removed: [ru] string/bluetooth_active_battery_level_untethered (format mismatch)
Removed: [ru] string/bluetooth_battery_level_untethered (format mismatch)

**Comment by ingbrzy** [comment]
https://github.com/ingbrzy/Xiaomi.eu-MIUIv12-XML-Compare/commit/7b9209aa4e2d5ddbce2cbc8a5f458a53c10fbbea

**Comment by mclaude74** [comment]
@ingbrzy 
Some "format mismatch" and "untranslatable" has been fixed. 
Will you re-scan filters?
