### ISSUE TITLE
Китайские иероглифы в звонилке

### ISSUE THREAD

**Issue by lllmiamilll** [ingbrzy/MA-XML-12-RUSSIAN#35]
Mi Note 10 Lite (toco)
12.0.2.0
[Image](https://photos.app.goo.gl/ts7pLacLnptwaZRy5)

**Comment by mclaude74** [comment]
@lllmiamilll 
Перевод есть. Скорее всего, это глюк ресурсов.
Данные приложения "Контакты и вызовы" пробовали очищать?
Еще варианты: 
- переключиться на английский язык в настройках, потом обратно на русский
- переключить тему

**Comment by lllmiamilll** [comment]
Попробовал все вышеуказанные действия. Результат тот же

**Comment by mclaude74** [comment]
@lllmiamilll 
Глобальная прошивка или от xiaomi.eu?
Судя по форуму 4pda, проблема носит единичный характер. 
Прошивка ставилась начисто?
Тема стандартная? 

Как вариант, попробовать:
https://4pda.ru/forum/index.php?showtopic=963744&st=4640#entry93910591
Но у меня в еженедельной (20.9.4) такой пункт отсутствует.

https://4pda.ru/forum/index.php?showtopic=892339&view=findpost&p=93133775

Или сменить Регион, если есть такой пункт в Настройки > Дополнительно

**Comment by lllmiamilll** [comment]
Xiaomi.eu
Прошивал сначала последнюю стабилку глобал через мифлэш, затем xiaomi.eu 11.0.1.0 через фастбут, затем обновился через рекавери до 12.0.2.0.
Темы все стандартные перепробовал.
Пункт Т9 так же отсутствует.
Короче пошел делать format data и ставить заново

**Comment by lllmiamilll** [comment]
Поставил систему начисто. Сначала clear all через miflash, затем установил рекавери, затем magisk, затем xiaomi.eu 12.0.2.0 через рекавери. та же хрень

**Comment by mclaude74** [comment]
@lllmiamilll 
Нужна именно "стабильная", почему не "еженедельная"?
Стабильные обычно прилично отстают от еженедельных и в них могут быть проблемы, которые уже исправлены в еженедельных.

Если в ветке вашего устройства у других пользователей на этой же стабильной наблюдается эта проблема,
надо отправлять багрепорт в xiaomi.eu.

Вообще-то, я к прошивкам отношения не имею, только добавляю перевод в свободное личное время.

**Comment by lllmiamilll** [comment]
@mclaude74 
поставил бы еженедельную, если бы была)

**Comment by mclaude74** [comment]
Вечером один вариант проверю, если получится напишу здесь

**Comment by lllmiamilll** [comment]
@mclaude74 
Нашел проблему. Я после установки восстанавливал приложения из аккаунта xiaomi.
Попробовал настроить как новое устройство - все стало на русском. Видимо косяк совместимости.
Спасибо за отзывчивость и уделенное время.
