### ISSUE TITLE
Недоперевод в настройках

### ISSUE THREAD

**Issue by noisexoma** [ingbrzy/MA-XML-12-RUSSIAN#39]
![IMG_20201018_183150](https://user-images.githubusercontent.com/5262136/96372645-79a81500-1170-11eb-9e0d-1958596f8843.jpg)
![IMG_20201018_183230](https://user-images.githubusercontent.com/5262136/96372651-7e6cc900-1170-11eb-9c66-573e442a370e.jpg)
![IMG_20201018_183252](https://user-images.githubusercontent.com/5262136/96372659-83317d00-1170-11eb-8854-65ff9ef468e4.jpg)
![IMG_20201018_183323](https://user-images.githubusercontent.com/5262136/96372662-875d9a80-1170-11eb-8581-60ac5fe5edfc.jpg)

**Comment by mclaude74** [comment]
@noisexoma 
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/issues/34

В отпуске сейчас. Работа над переводом продолжится в конце октября.
