### ISSUE TITLE
Auto fixes by translators.xiaomi.eu

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-12-RUSSIAN#47]
@ingbrzy, Hi!

Why are these strings removed from the repository?

https://github.com/ingbrzy/MA-XML-12-RUSSIAN/commit/a3be83552304927876d2d01df110c4c2f4643b94#

SecurityCenter.apk
```
    <string name="power_center_list_item_battery_health_model_voltage">%s В</string>
    <string name="power_center_list_item_battery_health_model_volume">%s мА·ч</string>
    <string name="power_center_list_item_battery_status_capacity">мА·ч</string>	
```

I putting these strings in the com.miui.securitycenter file
at the path /system/media/theme/default, in the Security app they are displayed without problems. 

![image](https://user-images.githubusercontent.com/45774262/100527677-75e2c600-31e5-11eb-8b56-a4a350426053.png)

**Comment by IgorEisberg** [comment]
https://github.com/redmaner/MA-XML-CHECK-RESOURCES/blob/master/MIUI12/MIUI12_untranslateable.xml#L797-L799

**Comment by mclaude74** [comment]
@IgorEisberg 
Thanks for info! 
I understand correctly, this is related to the assembly, and the only option is to add a translation for such strings through "themes"?
