### ISSUE TITLE
Медленный запуск приложений

### ISSUE THREAD

**Issue by KekessFT** [ingbrzy/MA-XML-12-RUSSIAN#50]
Добрый день.
Не могли бы Вы пересобрать framework.jar как положено.
Т.е. без удаления отладочной информации и без доп. сжатия.
Это влияет на последующую работу системы сильно!!!
Проверено на Стабильной 12.5.3
При запуске того же фейсбука 
Запуск с имеющимся framework.jar 4-5 секунд
Запуск с китайским framework.jar 0,2 секунды
Ну и соответственно так все приложения.

**Comment by mclaude74** [comment]
@KekessFT 
Приветствую! 
К сожалению, к сборке никакого отношения не имею, как упомянуто в первом посте темы: 
https://github.com/ingbrzy/MA-XML-12-RUSSIAN/issues/49

К команде xiaomi.eu непосредственного отношения не имею, только делаю перевод. 
Попробуйте написать на форуме xiaomi.eu, например, в теме 
https://xiaomi.eu/community/threads/info-confirmed-issues-weekly-faq.46800/ 
в частности, обратившись к Igor Eisberg
