### ISSUE TITLE
Недоперевод

### ISSUE THREAD

**Issue by m4l1na** [ingbrzy/MA-XML-12-RUSSIAN#61]
MIUI 12.5.4.0(RJQCNXM), Redmi 9T(lime). 

Недоперевод в приложении "Здоровье".
Вкладка "Здоровье" > иконка пользователя(Центр пользователя):
![IMG_20211202_104952](https://user-images.githubusercontent.com/75172822/144359907-0c612346-0c02-42ad-92c3-9eaa6e77bb50.jpg)

Вкладка "Здоровье" > иконка пользователя(Центр пользователя) > "Permission details":
![Screenshot_2021-12-02-10-17-14-252_com mi health](https://user-images.githubusercontent.com/75172822/144360049-0060f427-7ef2-45d5-b9c1-4c1a46970fef.jpg)
^ Внутри последующих пунктов также все на английском.

**Comment by mclaude74** [comment]
@Rifat921
Доперевод для приложения Здоровье добавлен 10.11.21 (если речь о прошивке от xiaomi.eu)
